# Generated by Django 4.0.3 on 2022-03-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.UUIDField(),
        ),
    ]
