# Generated by Django 4.0.3 on 2022-04-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_rename_money_spend_monthly_habit_money_spend_weekly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
