# Generated by Django 4.0.3 on 2022-04-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserActivateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used')),
                ('token', models.IntegerField(default=users.utils.generate_token)),
                ('expires_at', models.DateTimeField(default=users.utils.delay_activation_code_expiring, verbose_name='Expires at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to=settings.AUTH_USER_MODEL, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'User token for account activation',
                'verbose_name_plural': 'User tokens for account activation',
            },
        ),
    ]
