name: Push prod to heroku

on:
  push:
    branches: [ master ]
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'upwind-api' }}
  REGISTRY: ${{ 'registry.heroku.com/upwind-api' }}

jobs:
  build:
    name: Push to heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install heroku CLI
        run: |
          bash ./install_heroku_cli.sh
      - name: Docker login
        run: |
          docker login --username="actions@github.com" --password=$HEROKU_API_KEY registry.heroku.com

      - name: Docker build web
        run: |
          docker build -t $APP_NAME/web -f Dockerfile.prod .
          docker tag $APP_NAME/web $REGISTRY/web
          docker push $REGISTRY/web
      - name: Publish
        run: |
          heroku container:release web -a $APP_NAME